ZERO = b'\x00'

HEADER_FIELD_BYTES = 2
HEADER_FIELD_OFFSET = 0
HEADER_FIELD_VALUE = b'BM'

SIZE_BYTES = 4
SIZE_OFFSET = 2

APP_DATA_BYTES = 4
APP_DATA_OFFSET = 6

PIXEL_ARRAY_STARTING_ADDRESS_BYTES = 4
PIXEL_ARRAY_STARTING_ADDRESS_OFFSET = 10

HEADER_SIZE = HEADER_FIELD_BYTES + SIZE_BYTES + APP_DATA_BYTES + PIXEL_ARRAY_STARTING_ADDRESS_BYTES
